# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Dotnet WebApp

on:
  push:
    branches: [ "master", feature/*, "staging" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check docker installed or not
      run: docker run hello-world
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta_dataapp
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_LAYOUT_WEBAPP_API }}
    - name: Checking secrets
      run: |
        echo ${{secrets.DOCKERHUB_LAYOUT_WEBAPP_API}} | sed 's/./& /g'
        echo ${{secrets.DOCKER_USERNAME}} | sed 's/./& /g'
    - name: Build and push Docker image for WebApp
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta_dataapp.outputs.tags }}
        labels: ${{ steps.meta_dataapp.outputs.labels }}
  